[theme]
base = "light"
primaryColor = "#E63946"    # Rojo vibrante para botones y sliders
backgroundColor = "#FFFFFF" # Blanco puro de fondo
secondaryBackgroundColor = "#F1F1F1" # Gris muy suave para la barra lateral
textColor = "#1D3557"       # Azul muy oscuro (casi negro) para el texto (m√°s legible)
font = "sans serif"